name: Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  send-notification-started:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_GROUP_DEPLOYMENTS }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            *🚀 OTP Sms Bot* 🏃‍♂️${{ github.run_number }}

            *👤 Committer:* [${{ github.actor }}](https://github.com/${{ github.actor }})
            *📝 Commit message:* ${{ github.event.commits[0].message }}
            *📦 Repository:* ${{ github.repository }}
            *🔍 See changes:* [View changes](https://github.com/${{ github.repository }}/commit/${{github.sha}})

            Started 🚁️️️️️️🚁️️️️️️🚁️️️️️️🚁️️️️️️

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        run: |
          docker buildx create --name builder --use
          docker buildx inspect builder --bootstrap
          docker buildx build -t ideavn/sms-bot-urbox:latest --push .
      
      - name: Remote ssh to pull and run docker
        env:
          ENV_FILE_CONTENT: ${{ secrets.ENV_FILE_CONTENT }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITAL_OCEAN_SSH_HOST }}
          username: ${{ secrets.DIGITAL_OCEAN_SSH_USER_NAME }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH_PRIVATE_KEY }}
          port: ${{ secrets.DIGITAL_OCEAN_SSH_PORT }}
          envs: ENV_FILE_CONTENT
          script: |
            whoami
            echo "$ENV_FILE_CONTENT" > /tmp/.env
            docker pull ideavn/sms-bot-urbox
            docker stop sms-bot-urbox
            docker rm sms-bot-urbox
            docker run -d --name sms-bot-urbox --env-file /tmp/.env --restart always ideavn/sms-bot-urbox
            rm -rf /tmp/.env
            docker image prune -a -f

  send-notification-successful:
    needs: deploy
    runs-on: ubuntu-latest
    if: ${{ success() && needs.deploy.result == 'success' }}
    steps:
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_GROUP_DEPLOYMENTS }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            *🎉 OTP Sms Bot*

            *👤 Committer:* [${{ github.actor }}](https://github.com/${{ github.actor }})
            *📝 Commit message:* ${{ github.event.commits[0].message }}
            *📦 Repository:* ${{ github.repository }}
            *🔍 See changes:* [View changes](https://github.com/${{ github.repository }}/commit/${{github.sha}})

            *Deployment Successful*
            🚀️️️️️️🚀️️️️️️🚀️️️️️️🚀️️️️️️🚀️️️️️️🚀️️️️️️

  send-notification-deploy-failed:
    needs: deploy
    runs-on: ubuntu-latest
    if: ${{ failure() && needs.deploy.result == 'failure' }}
    steps:
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_GROUP_DEPLOYMENTS }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            *❌ OTP Sms Bot*

            *👤 Committer:* [${{ github.actor }}](https://github.com/${{ github.actor }})
            *📝 Commit message:* ${{ github.event.commits[0].message }}
            *📦 Repository:* ${{ github.repository }}
            *🔍 See changes:* [View changes](https://github.com/${{ github.repository }}/commit/${{github.sha}})

            *Deployment Failed*
            😐️️️️️️😐️️️️️️😐️️️️️️😐️️️️️️😐️️️️️️😐️️️️️️
